packages:
  - apps/*
  - packages/*
  - tooling/*

allowBuilds:
  '@prisma/client': true
  '@sentry/cli': true
  better-sqlite3: true
  core-js: true
  es5-ext: true
  esbuild: true
  msw: true
  protobufjs: true

catalog:
  # React 19

  # Database (Drizzle + Neon)

  # Better Auth
  "@better-auth/cli": "1.4.21"

  # Testing (Vitest + Testing Library)
  "vitest": "^4.1.4"
  "@vitest/ui": "^4.1.4"
  "happy-dom": "^20.8.9"

  # Utilities (Zod, Prettier,...)
  "@sentry/node": "^10.48.0"
  "@t3-oss/env-core": "^0.13.11"
  "@tailwindcss/postcss": "^4.2.1"
  "@tailwindcss/vite": "^4.2.2"

  # Tanstack (latest)
  "@tanstack/devtools-a11y": latest
  "@tanstack/devtools-vite": ^0.6.0
  "@tanstack/react-devtools": ^0.10.2
  "@tanstack/react-form": "^1.29.0"
  "@tanstack/react-form-devtools": latest
  "@tanstack/react-form-start": latest
  "@tanstack/react-query": "^5.99.0"
  "@tanstack/react-query-devtools": ^5.99.0
  "@tanstack/react-router": "^1.168.18"
  "@tanstack/react-router-devtools": "^1.166.13"
  "@tanstack/react-router-ssr-query": ^1.166.11
  "@tanstack/react-start": "^1.167.32"

  # Types
  "@types/node": "^25.6.0"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"
  "autoprefixer": "^10.4.27"
  "better-auth": "1.6.2"
  "lucide-react": "^1.8.0"
  "react": "^19.2.5"
  "react-dom": "^19.2.5"
  "simple-icons": "^16.16.0"

  # Tailwind CSS + UI
  "tailwindcss": "^4.2.1"
  "typescript": "^6.0.2"
  "vite": "^8.0.8"
  "zod": "^4.3.6"
