/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as dashboardLayoutRouteImport } from "./routes/(dashboard)/layout";
import { Route as authLayoutRouteImport } from "./routes/(auth)/layout";
import { Route as dashboardIndexRouteImport } from "./routes/(dashboard)/index";
import { Route as authSigninRouteImport } from "./routes/(auth)/signin";
import { Route as dashboardUsersIndexRouteImport } from "./routes/(dashboard)/users/index";
import { Route as dashboardSnippetsIndexRouteImport } from "./routes/(dashboard)/snippets/index";
import { Route as dashboardServicesIndexRouteImport } from "./routes/(dashboard)/services/index";
import { Route as dashboardProjectsIndexRouteImport } from "./routes/(dashboard)/projects/index";
import { Route as dashboardExperiencesIndexRouteImport } from "./routes/(dashboard)/experiences/index";
import { Route as dashboardBlogIndexRouteImport } from "./routes/(dashboard)/blog/index";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as dashboardSnippetsCreateRouteImport } from "./routes/(dashboard)/snippets/create";
import { Route as dashboardServicesCreateRouteImport } from "./routes/(dashboard)/services/create";
import { Route as dashboardProjectsCreateRouteImport } from "./routes/(dashboard)/projects/create";
import { Route as dashboardExperiencesCreateRouteImport } from "./routes/(dashboard)/experiences/create";
import { Route as dashboardBlogCreateRouteImport } from "./routes/(dashboard)/blog/create";
import { Route as ApiAiBlogAssistIndexRouteImport } from "./routes/api/ai/blog-assist/index";
import { Route as dashboardSnippetsSnippetIdEditRouteImport } from "./routes/(dashboard)/snippets/$snippetId.edit";
import { Route as dashboardServicesServiceIdEditRouteImport } from "./routes/(dashboard)/services/$serviceId.edit";
import { Route as dashboardProjectsProjectIdEditRouteImport } from "./routes/(dashboard)/projects/$projectId.edit";
import { Route as dashboardExperiencesExperienceIdEditRouteImport } from "./routes/(dashboard)/experiences/$experienceId.edit";
import { Route as dashboardBlogArticleIdEditRouteImport } from "./routes/(dashboard)/blog/$articleId.edit";

const dashboardLayoutRoute = dashboardLayoutRouteImport.update({
  id: "/(dashboard)",
  getParentRoute: () => rootRouteImport,
} as any);
const authLayoutRoute = authLayoutRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any);
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const authSigninRoute = authSigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => authLayoutRoute,
} as any);
const dashboardUsersIndexRoute = dashboardUsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardSnippetsIndexRoute = dashboardSnippetsIndexRouteImport.update({
  id: "/snippets/",
  path: "/snippets/",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardServicesIndexRoute = dashboardServicesIndexRouteImport.update({
  id: "/services/",
  path: "/services/",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardProjectsIndexRoute = dashboardProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardExperiencesIndexRoute =
  dashboardExperiencesIndexRouteImport.update({
    id: "/experiences/",
    path: "/experiences/",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardBlogIndexRoute = dashboardBlogIndexRouteImport.update({
  id: "/blog/",
  path: "/blog/",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const dashboardSnippetsCreateRoute = dashboardSnippetsCreateRouteImport.update({
  id: "/snippets/create",
  path: "/snippets/create",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardServicesCreateRoute = dashboardServicesCreateRouteImport.update({
  id: "/services/create",
  path: "/services/create",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardProjectsCreateRoute = dashboardProjectsCreateRouteImport.update({
  id: "/projects/create",
  path: "/projects/create",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardExperiencesCreateRoute =
  dashboardExperiencesCreateRouteImport.update({
    id: "/experiences/create",
    path: "/experiences/create",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardBlogCreateRoute = dashboardBlogCreateRouteImport.update({
  id: "/blog/create",
  path: "/blog/create",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const ApiAiBlogAssistIndexRoute = ApiAiBlogAssistIndexRouteImport.update({
  id: "/api/ai/blog-assist/",
  path: "/api/ai/blog-assist/",
  getParentRoute: () => rootRouteImport,
} as any);
const dashboardSnippetsSnippetIdEditRoute =
  dashboardSnippetsSnippetIdEditRouteImport.update({
    id: "/snippets/$snippetId/edit",
    path: "/snippets/$snippetId/edit",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardServicesServiceIdEditRoute =
  dashboardServicesServiceIdEditRouteImport.update({
    id: "/services/$serviceId/edit",
    path: "/services/$serviceId/edit",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardProjectsProjectIdEditRoute =
  dashboardProjectsProjectIdEditRouteImport.update({
    id: "/projects/$projectId/edit",
    path: "/projects/$projectId/edit",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardExperiencesExperienceIdEditRoute =
  dashboardExperiencesExperienceIdEditRouteImport.update({
    id: "/experiences/$experienceId/edit",
    path: "/experiences/$experienceId/edit",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardBlogArticleIdEditRoute =
  dashboardBlogArticleIdEditRouteImport.update({
    id: "/blog/$articleId/edit",
    path: "/blog/$articleId/edit",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/signin": typeof authSigninRoute;
  "/": typeof dashboardIndexRoute;
  "/blog/create": typeof dashboardBlogCreateRoute;
  "/experiences/create": typeof dashboardExperiencesCreateRoute;
  "/projects/create": typeof dashboardProjectsCreateRoute;
  "/services/create": typeof dashboardServicesCreateRoute;
  "/snippets/create": typeof dashboardSnippetsCreateRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/blog/": typeof dashboardBlogIndexRoute;
  "/experiences/": typeof dashboardExperiencesIndexRoute;
  "/projects/": typeof dashboardProjectsIndexRoute;
  "/services/": typeof dashboardServicesIndexRoute;
  "/snippets/": typeof dashboardSnippetsIndexRoute;
  "/users/": typeof dashboardUsersIndexRoute;
  "/blog/$articleId/edit": typeof dashboardBlogArticleIdEditRoute;
  "/experiences/$experienceId/edit": typeof dashboardExperiencesExperienceIdEditRoute;
  "/projects/$projectId/edit": typeof dashboardProjectsProjectIdEditRoute;
  "/services/$serviceId/edit": typeof dashboardServicesServiceIdEditRoute;
  "/snippets/$snippetId/edit": typeof dashboardSnippetsSnippetIdEditRoute;
  "/api/ai/blog-assist/": typeof ApiAiBlogAssistIndexRoute;
}
export interface FileRoutesByTo {
  "/signin": typeof authSigninRoute;
  "/": typeof dashboardIndexRoute;
  "/blog/create": typeof dashboardBlogCreateRoute;
  "/experiences/create": typeof dashboardExperiencesCreateRoute;
  "/projects/create": typeof dashboardProjectsCreateRoute;
  "/services/create": typeof dashboardServicesCreateRoute;
  "/snippets/create": typeof dashboardSnippetsCreateRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/blog": typeof dashboardBlogIndexRoute;
  "/experiences": typeof dashboardExperiencesIndexRoute;
  "/projects": typeof dashboardProjectsIndexRoute;
  "/services": typeof dashboardServicesIndexRoute;
  "/snippets": typeof dashboardSnippetsIndexRoute;
  "/users": typeof dashboardUsersIndexRoute;
  "/blog/$articleId/edit": typeof dashboardBlogArticleIdEditRoute;
  "/experiences/$experienceId/edit": typeof dashboardExperiencesExperienceIdEditRoute;
  "/projects/$projectId/edit": typeof dashboardProjectsProjectIdEditRoute;
  "/services/$serviceId/edit": typeof dashboardServicesServiceIdEditRoute;
  "/snippets/$snippetId/edit": typeof dashboardSnippetsSnippetIdEditRoute;
  "/api/ai/blog-assist": typeof ApiAiBlogAssistIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(auth)": typeof authLayoutRouteWithChildren;
  "/(dashboard)": typeof dashboardLayoutRouteWithChildren;
  "/(auth)/signin": typeof authSigninRoute;
  "/(dashboard)/": typeof dashboardIndexRoute;
  "/(dashboard)/blog/create": typeof dashboardBlogCreateRoute;
  "/(dashboard)/experiences/create": typeof dashboardExperiencesCreateRoute;
  "/(dashboard)/projects/create": typeof dashboardProjectsCreateRoute;
  "/(dashboard)/services/create": typeof dashboardServicesCreateRoute;
  "/(dashboard)/snippets/create": typeof dashboardSnippetsCreateRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/(dashboard)/blog/": typeof dashboardBlogIndexRoute;
  "/(dashboard)/experiences/": typeof dashboardExperiencesIndexRoute;
  "/(dashboard)/projects/": typeof dashboardProjectsIndexRoute;
  "/(dashboard)/services/": typeof dashboardServicesIndexRoute;
  "/(dashboard)/snippets/": typeof dashboardSnippetsIndexRoute;
  "/(dashboard)/users/": typeof dashboardUsersIndexRoute;
  "/(dashboard)/blog/$articleId/edit": typeof dashboardBlogArticleIdEditRoute;
  "/(dashboard)/experiences/$experienceId/edit": typeof dashboardExperiencesExperienceIdEditRoute;
  "/(dashboard)/projects/$projectId/edit": typeof dashboardProjectsProjectIdEditRoute;
  "/(dashboard)/services/$serviceId/edit": typeof dashboardServicesServiceIdEditRoute;
  "/(dashboard)/snippets/$snippetId/edit": typeof dashboardSnippetsSnippetIdEditRoute;
  "/api/ai/blog-assist/": typeof ApiAiBlogAssistIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/signin"
    | "/"
    | "/blog/create"
    | "/experiences/create"
    | "/projects/create"
    | "/services/create"
    | "/snippets/create"
    | "/api/auth/$"
    | "/blog/"
    | "/experiences/"
    | "/projects/"
    | "/services/"
    | "/snippets/"
    | "/users/"
    | "/blog/$articleId/edit"
    | "/experiences/$experienceId/edit"
    | "/projects/$projectId/edit"
    | "/services/$serviceId/edit"
    | "/snippets/$snippetId/edit"
    | "/api/ai/blog-assist/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/signin"
    | "/"
    | "/blog/create"
    | "/experiences/create"
    | "/projects/create"
    | "/services/create"
    | "/snippets/create"
    | "/api/auth/$"
    | "/blog"
    | "/experiences"
    | "/projects"
    | "/services"
    | "/snippets"
    | "/users"
    | "/blog/$articleId/edit"
    | "/experiences/$experienceId/edit"
    | "/projects/$projectId/edit"
    | "/services/$serviceId/edit"
    | "/snippets/$snippetId/edit"
    | "/api/ai/blog-assist";
  id:
    | "__root__"
    | "/(auth)"
    | "/(dashboard)"
    | "/(auth)/signin"
    | "/(dashboard)/"
    | "/(dashboard)/blog/create"
    | "/(dashboard)/experiences/create"
    | "/(dashboard)/projects/create"
    | "/(dashboard)/services/create"
    | "/(dashboard)/snippets/create"
    | "/api/auth/$"
    | "/(dashboard)/blog/"
    | "/(dashboard)/experiences/"
    | "/(dashboard)/projects/"
    | "/(dashboard)/services/"
    | "/(dashboard)/snippets/"
    | "/(dashboard)/users/"
    | "/(dashboard)/blog/$articleId/edit"
    | "/(dashboard)/experiences/$experienceId/edit"
    | "/(dashboard)/projects/$projectId/edit"
    | "/(dashboard)/services/$serviceId/edit"
    | "/(dashboard)/snippets/$snippetId/edit"
    | "/api/ai/blog-assist/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren;
  dashboardLayoutRoute: typeof dashboardLayoutRouteWithChildren;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiAiBlogAssistIndexRoute: typeof ApiAiBlogAssistIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(dashboard)": {
      id: "/(dashboard)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof dashboardLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)": {
      id: "/(auth)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof authLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(dashboard)/": {
      id: "/(dashboard)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof dashboardIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(auth)/signin": {
      id: "/(auth)/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof authSigninRouteImport;
      parentRoute: typeof authLayoutRoute;
    };
    "/(dashboard)/users/": {
      id: "/(dashboard)/users/";
      path: "/users";
      fullPath: "/users/";
      preLoaderRoute: typeof dashboardUsersIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/snippets/": {
      id: "/(dashboard)/snippets/";
      path: "/snippets";
      fullPath: "/snippets/";
      preLoaderRoute: typeof dashboardSnippetsIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/services/": {
      id: "/(dashboard)/services/";
      path: "/services";
      fullPath: "/services/";
      preLoaderRoute: typeof dashboardServicesIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/projects/": {
      id: "/(dashboard)/projects/";
      path: "/projects";
      fullPath: "/projects/";
      preLoaderRoute: typeof dashboardProjectsIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/experiences/": {
      id: "/(dashboard)/experiences/";
      path: "/experiences";
      fullPath: "/experiences/";
      preLoaderRoute: typeof dashboardExperiencesIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/blog/": {
      id: "/(dashboard)/blog/";
      path: "/blog";
      fullPath: "/blog/";
      preLoaderRoute: typeof dashboardBlogIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(dashboard)/snippets/create": {
      id: "/(dashboard)/snippets/create";
      path: "/snippets/create";
      fullPath: "/snippets/create";
      preLoaderRoute: typeof dashboardSnippetsCreateRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/services/create": {
      id: "/(dashboard)/services/create";
      path: "/services/create";
      fullPath: "/services/create";
      preLoaderRoute: typeof dashboardServicesCreateRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/projects/create": {
      id: "/(dashboard)/projects/create";
      path: "/projects/create";
      fullPath: "/projects/create";
      preLoaderRoute: typeof dashboardProjectsCreateRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/experiences/create": {
      id: "/(dashboard)/experiences/create";
      path: "/experiences/create";
      fullPath: "/experiences/create";
      preLoaderRoute: typeof dashboardExperiencesCreateRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/blog/create": {
      id: "/(dashboard)/blog/create";
      path: "/blog/create";
      fullPath: "/blog/create";
      preLoaderRoute: typeof dashboardBlogCreateRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/api/ai/blog-assist/": {
      id: "/api/ai/blog-assist/";
      path: "/api/ai/blog-assist";
      fullPath: "/api/ai/blog-assist/";
      preLoaderRoute: typeof ApiAiBlogAssistIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(dashboard)/snippets/$snippetId/edit": {
      id: "/(dashboard)/snippets/$snippetId/edit";
      path: "/snippets/$snippetId/edit";
      fullPath: "/snippets/$snippetId/edit";
      preLoaderRoute: typeof dashboardSnippetsSnippetIdEditRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/services/$serviceId/edit": {
      id: "/(dashboard)/services/$serviceId/edit";
      path: "/services/$serviceId/edit";
      fullPath: "/services/$serviceId/edit";
      preLoaderRoute: typeof dashboardServicesServiceIdEditRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/projects/$projectId/edit": {
      id: "/(dashboard)/projects/$projectId/edit";
      path: "/projects/$projectId/edit";
      fullPath: "/projects/$projectId/edit";
      preLoaderRoute: typeof dashboardProjectsProjectIdEditRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/experiences/$experienceId/edit": {
      id: "/(dashboard)/experiences/$experienceId/edit";
      path: "/experiences/$experienceId/edit";
      fullPath: "/experiences/$experienceId/edit";
      preLoaderRoute: typeof dashboardExperiencesExperienceIdEditRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/blog/$articleId/edit": {
      id: "/(dashboard)/blog/$articleId/edit";
      path: "/blog/$articleId/edit";
      fullPath: "/blog/$articleId/edit";
      preLoaderRoute: typeof dashboardBlogArticleIdEditRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
  }
}

interface authLayoutRouteChildren {
  authSigninRoute: typeof authSigninRoute;
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authSigninRoute: authSigninRoute,
};

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
);

interface dashboardLayoutRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute;
  dashboardBlogCreateRoute: typeof dashboardBlogCreateRoute;
  dashboardExperiencesCreateRoute: typeof dashboardExperiencesCreateRoute;
  dashboardProjectsCreateRoute: typeof dashboardProjectsCreateRoute;
  dashboardServicesCreateRoute: typeof dashboardServicesCreateRoute;
  dashboardSnippetsCreateRoute: typeof dashboardSnippetsCreateRoute;
  dashboardBlogIndexRoute: typeof dashboardBlogIndexRoute;
  dashboardExperiencesIndexRoute: typeof dashboardExperiencesIndexRoute;
  dashboardProjectsIndexRoute: typeof dashboardProjectsIndexRoute;
  dashboardServicesIndexRoute: typeof dashboardServicesIndexRoute;
  dashboardSnippetsIndexRoute: typeof dashboardSnippetsIndexRoute;
  dashboardUsersIndexRoute: typeof dashboardUsersIndexRoute;
  dashboardBlogArticleIdEditRoute: typeof dashboardBlogArticleIdEditRoute;
  dashboardExperiencesExperienceIdEditRoute: typeof dashboardExperiencesExperienceIdEditRoute;
  dashboardProjectsProjectIdEditRoute: typeof dashboardProjectsProjectIdEditRoute;
  dashboardServicesServiceIdEditRoute: typeof dashboardServicesServiceIdEditRoute;
  dashboardSnippetsSnippetIdEditRoute: typeof dashboardSnippetsSnippetIdEditRoute;
}

const dashboardLayoutRouteChildren: dashboardLayoutRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardBlogCreateRoute: dashboardBlogCreateRoute,
  dashboardExperiencesCreateRoute: dashboardExperiencesCreateRoute,
  dashboardProjectsCreateRoute: dashboardProjectsCreateRoute,
  dashboardServicesCreateRoute: dashboardServicesCreateRoute,
  dashboardSnippetsCreateRoute: dashboardSnippetsCreateRoute,
  dashboardBlogIndexRoute: dashboardBlogIndexRoute,
  dashboardExperiencesIndexRoute: dashboardExperiencesIndexRoute,
  dashboardProjectsIndexRoute: dashboardProjectsIndexRoute,
  dashboardServicesIndexRoute: dashboardServicesIndexRoute,
  dashboardSnippetsIndexRoute: dashboardSnippetsIndexRoute,
  dashboardUsersIndexRoute: dashboardUsersIndexRoute,
  dashboardBlogArticleIdEditRoute: dashboardBlogArticleIdEditRoute,
  dashboardExperiencesExperienceIdEditRoute:
    dashboardExperiencesExperienceIdEditRoute,
  dashboardProjectsProjectIdEditRoute: dashboardProjectsProjectIdEditRoute,
  dashboardServicesServiceIdEditRoute: dashboardServicesServiceIdEditRoute,
  dashboardSnippetsSnippetIdEditRoute: dashboardSnippetsSnippetIdEditRoute,
};

const dashboardLayoutRouteWithChildren = dashboardLayoutRoute._addFileChildren(
  dashboardLayoutRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  dashboardLayoutRoute: dashboardLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAiBlogAssistIndexRoute: ApiAiBlogAssistIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
